export const REPLY_WORD = {
  cohesion: ''
    + ':regional_indicator_c: '
    + ':o2: '
    + ':regional_indicator_h: '
    + ':regional_indicator_e: '
    + ':regional_indicator_s: '
    + ':regional_indicator_i: '
    + ':o2: '
    + ':regional_indicator_n:',
  django: ':regional_indicator_d: '
    + ':regional_indicator_j: '
    + ':regional_indicator_a: '
    + ':regional_indicator_n: '
    + ':regional_indicator_g: '
    + ':o2:',
  watermelon: ':watermelon: '
    + ':watermelon: '
    + ':watermelon: '
    + ':watermelon: '
    + ':watermelon:',
  fortyFiveMin: ':four: '
    + ':five: '
    + ':regional_indicator_m: '
    + ':regional_indicator_i: '
    + ':regional_indicator_n: ',
  success: ':regional_indicator_s: '
    + ':regional_indicator_u: '
    + ':regional_indicator_c: '
    + ':regional_indicator_c: '
    + ':regional_indicator_e: '
    + ':regional_indicator_s: '
    + ':regional_indicator_s: '
    + ':watermelon:',
  congratulation: ':regional_indicator_c: '
    + ':regional_indicator_o: '
    + ':regional_indicator_n: '
    + ':regional_indicator_g: '
    + ':regional_indicator_r: '
    + ':regional_indicator_a: '
    + ':regional_indicator_t: '
    + ':regional_indicator_u: '
    + ':regional_indicator_l: '
    + ':regional_indicator_a: '
    + ':regional_indicator_t: '
    + ':regional_indicator_i: '
    + ':regional_indicator_o: '
    + ':regional_indicator_n:',
};
